#!/usr/bin/env python3
"""critic-gate — Stop hook: after a medium or large (M/L) task asks Claude to run the critic agent.

The hook fires when Claude ends a turn and looks at what changed in the project
since the last user prompt:
  - production files. A change is detected by mtime, so edits made via Bash
    and by subagents are visible too;
  - lines — from git diff and from Edit/Write/MultiEdit/NotebookEdit calls in the transcript;
    new files count in full;
  - DB migrations and security config — per java-dev-flow such a task is no longer S.
Only files inside the project count: the git repository root, or the working directory without git.

Trivia does not count:
  - not code: documentation, images, archives, lock files;
  - tests, .claude/, build and IDE directories;
  - generated code: generated* directories, "DO NOT EDIT" / "@generated" headers;
  - Claude Code tooling: files inside a skill or plugin package, i.e. under
    a directory with SKILL.md or .claude-plugin/;
  - files where only whitespace, blank lines, comments, imports and package changed.
    In git with commits this is visible from the diff; without git — only for new files.

If the change looks like M or L and critic has not run since this prompt, the hook blocks
the stop (decision=block) and tells Claude what to do. At most one reminder per user prompt.

Configuration — environment variables, e.g. in "env" of ~/.claude/settings.json
or the project's .claude/settings.json:
  CRITIC_GATE=off             disable
  CRITIC_GATE_MIN_FILES=4     threshold: production files per turn
  CRITIC_GATE_MIN_LINES=150   threshold: changed lines in production files
  CRITIC_GATE_AGENT=critic    agent name
  CRITIC_GATE_DEBUG=1         print hook errors to stderr

Any internal error is a silent exit with code 0: the hook must not break the session.
"""

import json
import os
import re
import stat
import subprocess
import sys
import tempfile
import time
import traceback
from datetime import datetime, timezone


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except ValueError:
        return default


AGENT = os.environ.get("CRITIC_GATE_AGENT") or "critic"
MIN_FILES = env_int("CRITIC_GATE_MIN_FILES", 4)
MIN_LINES = env_int("CRITIC_GATE_MIN_LINES", 150)
STATE_DIR = os.environ.get("CRITIC_GATE_STATE_DIR") or os.path.join(tempfile.gettempdir(), "claude-critic-gate")

CLOCK_SKEW = 2.0  # seconds: slack for mtime rounding and clock drift
WALK_MAX_FILES = 50000  # directory walk without git: at most this many files
WALK_MAX_SECONDS = 3.0  # and no longer than this
MAX_COUNTED_BYTES = 1 << 20  # do not count lines in files over 1 MB
MAX_DIFF_FILES = 500  # beyond this no diff parsing is needed, the change is large anyway
SHOWN_FILES = 8
GIT_TIMEOUT = 4

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
AGENT_TOOLS = {"Agent", "Task"}

SKIP_DIRS = {
    ".git", ".hg", ".svn", ".claude", ".idea", ".vscode", ".fleet",
    "node_modules", "target", "build", "dist", "out", "obj",
    ".gradle", ".mvn", "__pycache__", ".venv", "venv", ".tox",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".next", ".nuxt",
    "coverage", ".terraform", ".cache",
    "generated", "generated-sources", "generated-test-sources",
}
DOC_EXT = {".md", ".mdx", ".markdown", ".txt", ".rst", ".adoc", ".org"}
DOC_NAMES = {"LICENSE", "LICENCE", "NOTICE", "AUTHORS", "CHANGELOG", "CONTRIBUTORS", "COPYING", "README", "CODEOWNERS"}
NON_CODE_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp", ".bmp", ".pdf",
    ".zip", ".jar", ".war", ".ear", ".class", ".skill", ".gz", ".tgz", ".tar", ".7z",
    ".woff", ".woff2", ".ttf", ".eot", ".mp3", ".mp4", ".mov", ".webm",
    ".log", ".csv", ".tsv", ".lock", ".iml", ".pyc", ".dll", ".exe", ".so", ".dylib", ".o", ".a",
}
LOCKFILES = {"package-lock.json", "pnpm-lock.yaml", "go.sum", ".DS_Store"}
# Generator headers: protoc, Go, jOOQ, OpenAPI Generator. Not "@generated": it would match @GeneratedValue.
GENERATED_RE = re.compile(
    rb"do not edit|code generated by|protocol buffer compiler|(file|class|code) (is|was) (auto[- ]?)?generated"
)

# A trivial line: after strip it starts with a comment marker (by file extension) or with import/package.
C_COMMENTS = ("//", "/*", "*")
HASH_COMMENTS = ("#",)
COMMENT_MARKERS = {
    ".java": C_COMMENTS, ".kt": C_COMMENTS, ".kts": C_COMMENTS, ".scala": C_COMMENTS, ".groovy": C_COMMENTS,
    ".go": C_COMMENTS, ".js": C_COMMENTS, ".jsx": C_COMMENTS, ".ts": C_COMMENTS, ".tsx": C_COMMENTS,
    ".mjs": C_COMMENTS, ".cjs": C_COMMENTS, ".c": C_COMMENTS, ".h": C_COMMENTS, ".cpp": C_COMMENTS,
    ".hpp": C_COMMENTS, ".cs": C_COMMENTS, ".swift": C_COMMENTS, ".rs": C_COMMENTS,
    ".php": C_COMMENTS + HASH_COMMENTS, ".tf": C_COMMENTS + HASH_COMMENTS,
    ".py": HASH_COMMENTS, ".rb": HASH_COMMENTS, ".sh": HASH_COMMENTS, ".bash": HASH_COMMENTS,
    ".zsh": HASH_COMMENTS, ".yml": HASH_COMMENTS, ".yaml": HASH_COMMENTS, ".toml": HASH_COMMENTS,
    ".conf": HASH_COMMENTS, ".cfg": HASH_COMMENTS, ".properties": ("#", "!"), ".ini": ("#", ";"),
    ".sql": ("--", "/*", "*"), ".xml": ("<!--", "-->"), ".html": ("<!--", "-->"),
}
NAME_COMMENT_MARKERS = {"Dockerfile": HASH_COMMENTS, "Makefile": HASH_COMMENTS}
IMPORT_EXT = {".java", ".kt", ".kts", ".scala", ".groovy", ".go", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".py"}
IMPORT_PREFIXES = ("import ", "package ")

TEST_RE = re.compile(
    r"(^|/)(src/(test|it|integration-?[tT]est|testFixtures)|tests?|__tests__|__mocks__|spec|specs|testdata|fixtures)/"
    r"|[a-z0-9](Test|Tests|TestCase|IT|ITCase|Spec)\.(java|kt|kts|groovy|scala)$"
    r"|(_test\.(go|py|rb|exs?)|_spec\.rb|\.(test|spec)\.(js|jsx|ts|tsx|mjs|cjs))$"
    r"|(^|/)(test_[^/]*\.py|conftest\.py)$"
)
MIGRATION_RE = re.compile(
    r"(^|/)(db/(changelog|migration|migrations|migrate)|migrations?|liquibase|flyway|alembic)/"
    r"|\.sql$"
    r"|(^|/)[^/]*changelog[^/]*\.(xml|ya?ml|json)$",
    re.IGNORECASE,
)
SECURITY_RE = re.compile(
    r"(^|/)(security|auth|authz|authorization)/"
    r"|(^|/)[^/]*(Security|Auth[A-Z0-9]|Authenticat|Authoriz|OAuth|Jwt|JWT|Permission|Acl[A-Z.])[^/]*\.(java|kt|scala|groovy)$"
)
TS_RE = re.compile(r"^(\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d)(\.\d+)?(Z|[+-]\d\d:?\d\d)?$")
# User entries written by Claude Code itself, not by a human (for transcripts without the origin field).
SYSTEM_PREFIXES = (
    "<task-notification", "<local-command", "<bash-stdout", "<bash-stderr",
    "Stop hook feedback", "[Request interrupted", "Caveat:",
)
GIT_ENV = dict(os.environ, GIT_OPTIONAL_LOCKS="0", LC_ALL="C")


class Turn(object):
    def __init__(self, prompt_ts, prompt_id, critic_launched, edits):
        self.prompt_ts = prompt_ts
        self.prompt_id = prompt_id
        self.critic_launched = critic_launched
        self.edits = edits  # realpath -> changed lines from tool calls


def parse_ts(value):
    match = TS_RE.match(value) if isinstance(value, str) else None
    if not match:
        return None
    base = datetime.strptime(match.group(1), "%Y-%m-%dT%H:%M:%S").replace(tzinfo=timezone.utc).timestamp()
    frac = float(match.group(2)) if match.group(2) else 0.0
    zone = match.group(3)
    offset = 0
    if zone and zone != "Z":
        digits = zone[1:].replace(":", "")
        offset = (1 if zone[0] == "+" else -1) * (int(digits[:2]) * 3600 + int(digits[2:]) * 60)
    return base + frac - offset


def is_human_prompt(entry):
    if entry.get("type") != "user" or entry.get("isMeta") or entry.get("isSidechain"):
        return False
    origin = entry.get("origin")
    if isinstance(origin, dict) and origin.get("kind"):
        return origin.get("kind") == "human"
    content = (entry.get("message") or {}).get("content")
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        if any(isinstance(block, dict) and block.get("type") == "tool_result" for block in content):
            return False
        text = " ".join(
            block.get("text") or "" for block in content if isinstance(block, dict) and block.get("type") == "text"
        )
    else:
        return False
    text = text.lstrip()
    return bool(text) and not text.startswith(SYSTEM_PREFIXES)


def is_critic(subagent_type):
    return isinstance(subagent_type, str) and (subagent_type == AGENT or subagent_type.endswith(":" + AGENT))


def count_lines(text):
    if not isinstance(text, str) or not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def edit_size(name, tool_input, cwd):
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(path, str) or not path:
        return None, 0
    if name == "Write":
        lines = count_lines(tool_input.get("content"))
    elif name == "Edit":
        lines = max(count_lines(tool_input.get("old_string")), count_lines(tool_input.get("new_string")))
    elif name == "MultiEdit":
        lines = sum(
            max(count_lines(edit.get("old_string")), count_lines(edit.get("new_string")))
            for edit in tool_input.get("edits") or []
            if isinstance(edit, dict)
        )
    else:  # NotebookEdit
        lines = count_lines(tool_input.get("new_source"))
    return os.path.realpath(os.path.join(cwd, path)), lines


def read_turn(transcript_path, cwd):
    """Walks the transcript backwards to the last human prompt."""
    with open(transcript_path, "rb") as transcript:
        raw_lines = transcript.read().splitlines()
    critic_launched = False
    edits = {}
    for raw in reversed(raw_lines):
        if not raw.strip():
            continue
        try:
            entry = json.loads(raw)
        except ValueError:
            continue
        if not isinstance(entry, dict):
            continue
        if entry.get("type") == "assistant":
            content = (entry.get("message") or {}).get("content")
            for block in content if isinstance(content, list) else []:
                if not isinstance(block, dict) or block.get("type") != "tool_use":
                    continue
                name = block.get("name")
                tool_input = block.get("input") if isinstance(block.get("input"), dict) else {}
                if name in AGENT_TOOLS and is_critic(tool_input.get("subagent_type")):
                    critic_launched = True
                elif name in EDIT_TOOLS:
                    path, lines = edit_size(name, tool_input, cwd)
                    if path:
                        edits[path] = edits.get(path, 0) + lines
        elif is_human_prompt(entry):
            prompt_ts = parse_ts(entry.get("timestamp"))
            if prompt_ts is None:
                return None
            prompt_id = str(entry.get("uuid") or entry.get("promptId") or entry.get("timestamp"))
            return Turn(prompt_ts, prompt_id, critic_launched, edits)
    return None


def git(root, *args):
    try:
        result = subprocess.run(
            ["git", "-C", root, "-c", "core.quotePath=false"] + list(args),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, timeout=GIT_TIMEOUT, env=GIT_ENV,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout if result.returncode == 0 else None


def project_root(cwd):
    out = git(cwd, "rev-parse", "--show-toplevel")
    if out and out.strip():
        return os.path.realpath(os.fsdecode(out.strip())), True
    return os.path.realpath(cwd), False


def git_candidates(root, since):
    """Dirty and untracked files plus files from commits made during the turn. Value — the git status or "log"."""
    found = {}
    out = git(root, "status", "--porcelain=v1", "-z", "--untracked-files=all")
    tokens = out.split(b"\0") if out else []
    i = 0
    while i < len(tokens):
        token = tokens[i]
        i += 1
        if len(token) < 4:
            continue
        status = token[:2]
        if b"R" in status or b"C" in status:
            i += 1  # the rename source path follows
        found[os.path.realpath(os.path.join(root, os.fsdecode(token[3:])))] = os.fsdecode(status)
    out = git(root, "log", "--since=@%d" % int(since), "--name-only", "--no-renames", "--format=")
    for line in out.splitlines() if out else []:
        if line.strip():
            found.setdefault(os.path.realpath(os.path.join(root, os.fsdecode(line))), "log")
    return found


def walk_candidates(root, since):
    """Without git: working directory files with mtime after the prompt. Value — "new" or "changed"."""
    found = {}
    if root in (os.path.realpath(os.path.expanduser("~")), os.path.realpath(os.sep)):
        return found
    deadline = time.monotonic() + WALK_MAX_SECONDS
    seen = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in dirnames if name not in SKIP_DIRS]
        for name in filenames:
            path = os.path.join(dirpath, name)
            st = file_stat(path)
            if st is not None and st.st_mtime >= since:
                found[os.path.realpath(path)] = "new" if getattr(st, "st_birthtime", 0) >= since else "changed"
        seen += len(filenames)
        if seen > WALK_MAX_FILES or time.monotonic() > deadline:
            break
    return found


def file_stat(path):
    try:
        st = os.stat(path)
    except OSError:
        return None
    return st if stat.S_ISREG(st.st_mode) else None


def read_text(path):
    """Contents of a text file up to 1 MB, otherwise None."""
    try:
        if os.path.getsize(path) > MAX_COUNTED_BYTES:
            return None
        with open(path, "rb") as source:
            data = source.read()
    except OSError:
        return None
    return None if b"\0" in data[:8000] else data


def relative_inside(root, path):
    rel = os.path.relpath(path, root)
    if rel == os.curdir or rel == os.pardir or rel.startswith(os.pardir + os.sep):
        return None
    return rel.replace(os.sep, "/")


def is_production(rel):
    parts = rel.split("/")
    if any(part in SKIP_DIRS for part in parts[:-1]):
        return False
    name = parts[-1]
    if name in LOCKFILES or name.upper() in DOC_NAMES:
        return False
    ext = os.path.splitext(name)[1].lower()
    if ext in DOC_EXT or ext in NON_CODE_EXT:
        return False
    return not TEST_RE.search(rel)


def is_tooling(root, path, cache):
    """A file inside a Claude Code skill or plugin package: tooling, not production code."""
    directory = os.path.dirname(path)
    visited = []
    result = False
    while True:
        if directory in cache:
            result = cache[directory]
            break
        visited.append(directory)
        if os.path.isfile(os.path.join(directory, "SKILL.md")) or os.path.isdir(os.path.join(directory, ".claude-plugin")):
            result = True
            break
        parent = os.path.dirname(directory)
        if directory == root or parent == directory:
            break
        directory = parent
    for seen in visited:
        cache[seen] = result
    return result


def is_generated(path):
    try:
        with open(path, "rb") as source:
            head = source.read(2048).lower()
    except OSError:
        return False
    return GENERATED_RE.search(head) is not None


def trivial_prefixes(rel):
    name = rel.rsplit("/", 1)[-1]
    ext = os.path.splitext(name)[1].lower()
    comments = COMMENT_MARKERS.get(ext) or NAME_COMMENT_MARKERS.get(name, ())
    return comments + (IMPORT_PREFIXES if ext in IMPORT_EXT else ())


def is_trivial_line(text, prefixes):
    stripped = text.strip()
    return not stripped or stripped.startswith(prefixes)


def substantive_lines(rel, data):
    """Lines of a new file excluding blank lines, comments, imports and package."""
    prefixes = trivial_prefixes(rel)
    return sum(1 for line in data.decode("utf-8", "replace").splitlines() if not is_trivial_line(line, prefixes))


def header_path(line):
    """The path from `diff --git a/<p> b/<p>`; with --no-renames both halves match. Quoted paths — None."""
    body = line[len("diff --git a/"):] if line.startswith("diff --git a/") else ""
    half = (len(body) - 3) // 2
    if half > 0 and body[half:half + 3] == " b/" and body[:half] == body[half + 3:]:
        return body[:half]
    return None


def diff_against_head(root, rels):
    """Substantive lines of `git diff HEAD` per file: rel -> [added, removed].

    Git drops whitespace and blank lines itself (-w, --ignore-blank-lines); comments,
    imports and package are dropped by is_trivial_line. A file missing from the result has no substantive edits.
    None means no parsing, and files are counted as before: no commits, too many files,
    or a path from the diff could not be matched.
    """
    if not rels or len(rels) > MAX_DIFF_FILES:
        return None
    out = git(root, "diff", "HEAD", "-U0", "-w", "--ignore-blank-lines", "--no-color", "--no-ext-diff",
              "--no-renames", "--", *rels)
    if out is None:
        return None
    stats = dict((rel, [0, 0]) for rel in rels)
    current, prefixes, in_hunk = None, (), False
    for raw in out.split(b"\n"):
        line = raw.decode("utf-8", "replace")
        if line.startswith("diff --git "):
            current, in_hunk = header_path(line), False
            if current not in stats:
                return None  # when in doubt, count the file rather than skip it
            prefixes = trivial_prefixes(current)
        elif line.startswith("Binary files ") and current is not None:
            stats[current] = [1, 1]
        elif line.startswith("@@"):
            in_hunk = True
        elif in_hunk and current is not None and line[:1] in ("+", "-"):
            if not is_trivial_line(line[1:], prefixes):
                stats[current][0 if line[0] == "+" else 1] += 1
    return stats


def measure(root, is_git, turn):
    since = turn.prompt_ts - CLOCK_SKEW
    candidates = git_candidates(root, since) if is_git else walk_candidates(root, since)
    for path in turn.edits:
        candidates.setdefault(path, "edit")
    tooling_cache = {}
    changed = []  # (path, rel, status)
    for path, status in candidates.items():
        rel = relative_inside(root, path)
        if rel is None or not is_production(rel):
            continue
        st = file_stat(path)
        if st is None or st.st_mtime < since:
            continue
        if is_tooling(root, path, tooling_cache) or is_generated(path):
            continue
        changed.append((path, rel, status))
    # Only tracked files changed right now go to the diff: commits made during the turn and new files are estimated separately.
    diff = diff_against_head(root, [rel for _, rel, status in changed if status not in ("??", "log", "edit")]) \
        if is_git else None
    prod, risky = [], []
    for path, rel, status in changed:
        from_tools = turn.edits.get(path, 0)
        if diff is not None and rel in diff:
            lines = max(diff[rel])
            if lines == 0:
                continue  # whitespace, comments, imports only
            if from_tools:
                lines = min(lines, from_tools)  # the diff may include edits made before this prompt
        elif status in ("??", "new"):
            data = read_text(path)
            lines = substantive_lines(rel, data) if data is not None else from_tools
            if data is not None and lines == 0:
                continue  # a new file of comments only
        else:
            lines = from_tools
        prod.append((rel, lines))
        if MIGRATION_RE.search(rel) or SECURITY_RE.search(rel):
            risky.append(rel)
    prod.sort()
    risky.sort()
    return prod, risky


def state_file(session_id):
    return os.path.join(STATE_DIR, re.sub(r"[^A-Za-z0-9_.-]", "_", session_id) or "unknown")


def already_reminded(session_id, prompt_id):
    try:
        with open(state_file(session_id), encoding="utf-8") as state:
            return state.read().strip() == prompt_id
    except OSError:
        return False


def remember_reminder(session_id, prompt_id):
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        with open(state_file(session_id), "w", encoding="utf-8") as state:
            state.write(prompt_id)
    except OSError:
        pass


def build_reason(prod, total_lines, risky):
    shown = [rel for rel, _ in prod[:SHOWN_FILES]]
    files = ", ".join(shown)
    if len(prod) > len(shown):
        files += " and %d more" % (len(prod) - len(shown))
    stats = "production files: %d" % len(prod)
    if total_lines:
        stats += ", changed lines: ~%d" % total_lines
    if risky:
        stats += "; migrations or security touched: " + ", ".join(risky[:SHOWN_FILES])
    return (
        "critic-gate: the change looks like a medium or large (M/L) task, and the {agent} agent has not run "
        "since the last user prompt. Changed {stats}.\n"
        "Files: {files}\n\n"
        "Before the final answer run the {agent} agent (Agent, subagent_type: \"{agent}\") on these changes. "
        "Pass it the diff scope or the file list, 2–5 lines on what was done, the requirements or spec "
        "if any, the task size and what is known about production: load, data volumes, API and event "
        "consumers, deploy method. Fix confirmed blockers (a bug — test first), bring risks and questions "
        "to the user.\n"
        "If the critic is not needed here — a mechanical edit, rename, formatting, generated "
        "code — tell the user why in one line and end the turn. If the {agent} agent is not among "
        "the available ones, tell the user it must be put into ~/.claude/agents/ and a new session started."
    ).format(agent=AGENT, stats=stats, files=files)


def main():
    try:
        payload = json.load(sys.stdin)
    except ValueError:
        return
    if not isinstance(payload, dict) or payload.get("stop_hook_active"):
        return
    if os.environ.get("CRITIC_GATE", "").strip().lower() in ("0", "off", "false", "no"):
        return
    transcript = payload.get("transcript_path")
    if not isinstance(transcript, str) or not os.path.isfile(transcript):
        return
    cwd = payload.get("cwd") if isinstance(payload.get("cwd"), str) else os.getcwd()
    turn = read_turn(transcript, cwd)
    if turn is None or turn.critic_launched:
        return
    session_id = str(payload.get("session_id") or "unknown")
    if already_reminded(session_id, turn.prompt_id):
        return
    root, is_git = project_root(cwd)
    prod, risky = measure(root, is_git, turn)
    total_lines = sum(lines for _, lines in prod)
    if len(prod) < MIN_FILES and total_lines < MIN_LINES and not risky:
        return
    remember_reminder(session_id, turn.prompt_id)
    # ASCII JSON: the output does not depend on the hook process locale
    print(json.dumps({"decision": "block", "reason": build_reason(prod, total_lines, risky)}))


if __name__ == "__main__":
    try:
        main()
    except Exception:  # the hook must not break the session
        if os.environ.get("CRITIC_GATE_DEBUG"):
            traceback.print_exc()
    sys.exit(0)
