#!/usr/bin/env python3
"""critic-gate — Stop-хук: после задачи размера M или L просит Claude запустить агента critic.

Хук срабатывает, когда Claude заканчивает ход, и смотрит, что изменилось в проекте
с последнего запроса пользователя:
  - production-файлы. Изменение определяется по mtime, поэтому правки через Bash
    и субагентов тоже видны;
  - строки — по git diff и вызовам Edit/Write/MultiEdit/NotebookEdit в транскрипте;
    новые файлы считаются целиком;
  - миграции БД и security-конфиг — по java-dev-flow такая задача уже не S.
Учитываются только файлы внутри проекта: корень git-репозитория, а без git — рабочий каталог.

Пустяки не считаются:
  - не код: документация, картинки, архивы, lock-файлы;
  - тесты, .claude/, каталоги сборки и IDE;
  - сгенерированный код: каталоги generated*, заголовки «DO NOT EDIT», «@generated»;
  - инструменты Claude Code: файлы внутри пакета скилла или плагина, то есть под
    каталогом с SKILL.md или .claude-plugin/;
  - файлы, где поменялись только пробелы, пустые строки, комментарии, import и package.
    В git с коммитами это видно по diff, без git — только для новых файлов.

Если изменение похоже на M или L, а critic с этого запроса не запускался, хук блокирует
остановку (decision=block) и объясняет Claude, что сделать. На один запрос пользователя —
не больше одного напоминания.

Настройка — переменные окружения, например в "env" файла ~/.claude/settings.json
или .claude/settings.json проекта:
  CRITIC_GATE=off             выключить
  CRITIC_GATE_MIN_FILES=4     порог: production-файлов за ход
  CRITIC_GATE_MIN_LINES=150   порог: изменённых строк в production-файлах
  CRITIC_GATE_AGENT=critic    имя агента
  CRITIC_GATE_DEBUG=1         печатать ошибки хука в stderr

Любая внутренняя ошибка — тихий выход с кодом 0: хук не должен ломать сессию.
"""

import json
import os
import re
import stat
import subprocess
import sys
import tempfile
import time
import traceback
from datetime import datetime, timezone


def env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except ValueError:
        return default


AGENT = os.environ.get("CRITIC_GATE_AGENT") or "critic"
MIN_FILES = env_int("CRITIC_GATE_MIN_FILES", 4)
MIN_LINES = env_int("CRITIC_GATE_MIN_LINES", 150)
STATE_DIR = os.environ.get("CRITIC_GATE_STATE_DIR") or os.path.join(tempfile.gettempdir(), "claude-critic-gate")

CLOCK_SKEW = 2.0  # секунды: запас на округление mtime и разницу часов
WALK_MAX_FILES = 50000  # обход каталога без git: не больше стольких файлов
WALK_MAX_SECONDS = 3.0  # и не дольше
MAX_COUNTED_BYTES = 1 << 20  # строки в файлах больше 1 МБ не считаем
MAX_DIFF_FILES = 500  # больше — разбор diff не нужен, изменение и так большое
SHOWN_FILES = 8
GIT_TIMEOUT = 4

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
AGENT_TOOLS = {"Agent", "Task"}

SKIP_DIRS = {
    ".git", ".hg", ".svn", ".claude", ".idea", ".vscode", ".fleet",
    "node_modules", "target", "build", "dist", "out", "obj",
    ".gradle", ".mvn", "__pycache__", ".venv", "venv", ".tox",
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".next", ".nuxt",
    "coverage", ".terraform", ".cache",
    "generated", "generated-sources", "generated-test-sources",
}
DOC_EXT = {".md", ".mdx", ".markdown", ".txt", ".rst", ".adoc", ".org"}
DOC_NAMES = {"LICENSE", "LICENCE", "NOTICE", "AUTHORS", "CHANGELOG", "CONTRIBUTORS", "COPYING", "README", "CODEOWNERS"}
NON_CODE_EXT = {
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp", ".bmp", ".pdf",
    ".zip", ".jar", ".war", ".ear", ".class", ".skill", ".gz", ".tgz", ".tar", ".7z",
    ".woff", ".woff2", ".ttf", ".eot", ".mp3", ".mp4", ".mov", ".webm",
    ".log", ".csv", ".tsv", ".lock", ".iml", ".pyc", ".dll", ".exe", ".so", ".dylib", ".o", ".a",
}
LOCKFILES = {"package-lock.json", "pnpm-lock.yaml", "go.sum", ".DS_Store"}
# Заголовки генераторов: protoc, Go, jOOQ, OpenAPI Generator. Не "@generated": совпадёт с @GeneratedValue.
GENERATED_RE = re.compile(
    rb"do not edit|code generated by|protocol buffer compiler|(file|class|code) (is|was) (auto[- ]?)?generated"
)

# Строка-пустяк: после strip начинается с маркера комментария (по расширению файла) или с import/package.
C_COMMENTS = ("//", "/*", "*")
HASH_COMMENTS = ("#",)
COMMENT_MARKERS = {
    ".java": C_COMMENTS, ".kt": C_COMMENTS, ".kts": C_COMMENTS, ".scala": C_COMMENTS, ".groovy": C_COMMENTS,
    ".go": C_COMMENTS, ".js": C_COMMENTS, ".jsx": C_COMMENTS, ".ts": C_COMMENTS, ".tsx": C_COMMENTS,
    ".mjs": C_COMMENTS, ".cjs": C_COMMENTS, ".c": C_COMMENTS, ".h": C_COMMENTS, ".cpp": C_COMMENTS,
    ".hpp": C_COMMENTS, ".cs": C_COMMENTS, ".swift": C_COMMENTS, ".rs": C_COMMENTS,
    ".php": C_COMMENTS + HASH_COMMENTS, ".tf": C_COMMENTS + HASH_COMMENTS,
    ".py": HASH_COMMENTS, ".rb": HASH_COMMENTS, ".sh": HASH_COMMENTS, ".bash": HASH_COMMENTS,
    ".zsh": HASH_COMMENTS, ".yml": HASH_COMMENTS, ".yaml": HASH_COMMENTS, ".toml": HASH_COMMENTS,
    ".conf": HASH_COMMENTS, ".cfg": HASH_COMMENTS, ".properties": ("#", "!"), ".ini": ("#", ";"),
    ".sql": ("--", "/*", "*"), ".xml": ("<!--", "-->"), ".html": ("<!--", "-->"),
}
NAME_COMMENT_MARKERS = {"Dockerfile": HASH_COMMENTS, "Makefile": HASH_COMMENTS}
IMPORT_EXT = {".java", ".kt", ".kts", ".scala", ".groovy", ".go", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".py"}
IMPORT_PREFIXES = ("import ", "package ")

TEST_RE = re.compile(
    r"(^|/)(src/(test|it|integration-?[tT]est|testFixtures)|tests?|__tests__|__mocks__|spec|specs|testdata|fixtures)/"
    r"|[a-z0-9](Test|Tests|TestCase|IT|ITCase|Spec)\.(java|kt|kts|groovy|scala)$"
    r"|(_test\.(go|py|rb|exs?)|_spec\.rb|\.(test|spec)\.(js|jsx|ts|tsx|mjs|cjs))$"
    r"|(^|/)(test_[^/]*\.py|conftest\.py)$"
)
MIGRATION_RE = re.compile(
    r"(^|/)(db/(changelog|migration|migrations|migrate)|migrations?|liquibase|flyway|alembic)/"
    r"|\.sql$"
    r"|(^|/)[^/]*changelog[^/]*\.(xml|ya?ml|json)$",
    re.IGNORECASE,
)
SECURITY_RE = re.compile(
    r"(^|/)(security|auth|authz|authorization)/"
    r"|(^|/)[^/]*(Security|Auth[A-Z0-9]|Authenticat|Authoriz|OAuth|Jwt|JWT|Permission|Acl[A-Z.])[^/]*\.(java|kt|scala|groovy)$"
)
TS_RE = re.compile(r"^(\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d)(\.\d+)?(Z|[+-]\d\d:?\d\d)?$")
# Пользовательские записи, которые пишет сам Claude Code, а не человек (для транскриптов без поля origin).
SYSTEM_PREFIXES = (
    "<task-notification", "<local-command", "<bash-stdout", "<bash-stderr",
    "Stop hook feedback", "[Request interrupted", "Caveat:",
)
GIT_ENV = dict(os.environ, GIT_OPTIONAL_LOCKS="0", LC_ALL="C")


class Turn(object):
    def __init__(self, prompt_ts, prompt_id, critic_launched, edits):
        self.prompt_ts = prompt_ts
        self.prompt_id = prompt_id
        self.critic_launched = critic_launched
        self.edits = edits  # realpath -> изменённые строки по вызовам инструментов


def parse_ts(value):
    match = TS_RE.match(value) if isinstance(value, str) else None
    if not match:
        return None
    base = datetime.strptime(match.group(1), "%Y-%m-%dT%H:%M:%S").replace(tzinfo=timezone.utc).timestamp()
    frac = float(match.group(2)) if match.group(2) else 0.0
    zone = match.group(3)
    offset = 0
    if zone and zone != "Z":
        digits = zone[1:].replace(":", "")
        offset = (1 if zone[0] == "+" else -1) * (int(digits[:2]) * 3600 + int(digits[2:]) * 60)
    return base + frac - offset


def is_human_prompt(entry):
    if entry.get("type") != "user" or entry.get("isMeta") or entry.get("isSidechain"):
        return False
    origin = entry.get("origin")
    if isinstance(origin, dict) and origin.get("kind"):
        return origin.get("kind") == "human"
    content = (entry.get("message") or {}).get("content")
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        if any(isinstance(block, dict) and block.get("type") == "tool_result" for block in content):
            return False
        text = " ".join(
            block.get("text") or "" for block in content if isinstance(block, dict) and block.get("type") == "text"
        )
    else:
        return False
    text = text.lstrip()
    return bool(text) and not text.startswith(SYSTEM_PREFIXES)


def is_critic(subagent_type):
    return isinstance(subagent_type, str) and (subagent_type == AGENT or subagent_type.endswith(":" + AGENT))


def count_lines(text):
    if not isinstance(text, str) or not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def edit_size(name, tool_input, cwd):
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not isinstance(path, str) or not path:
        return None, 0
    if name == "Write":
        lines = count_lines(tool_input.get("content"))
    elif name == "Edit":
        lines = max(count_lines(tool_input.get("old_string")), count_lines(tool_input.get("new_string")))
    elif name == "MultiEdit":
        lines = sum(
            max(count_lines(edit.get("old_string")), count_lines(edit.get("new_string")))
            for edit in tool_input.get("edits") or []
            if isinstance(edit, dict)
        )
    else:  # NotebookEdit
        lines = count_lines(tool_input.get("new_source"))
    return os.path.realpath(os.path.join(cwd, path)), lines


def read_turn(transcript_path, cwd):
    """Идёт по транскрипту с конца до последнего запроса человека."""
    with open(transcript_path, "rb") as transcript:
        raw_lines = transcript.read().splitlines()
    critic_launched = False
    edits = {}
    for raw in reversed(raw_lines):
        if not raw.strip():
            continue
        try:
            entry = json.loads(raw)
        except ValueError:
            continue
        if not isinstance(entry, dict):
            continue
        if entry.get("type") == "assistant":
            content = (entry.get("message") or {}).get("content")
            for block in content if isinstance(content, list) else []:
                if not isinstance(block, dict) or block.get("type") != "tool_use":
                    continue
                name = block.get("name")
                tool_input = block.get("input") if isinstance(block.get("input"), dict) else {}
                if name in AGENT_TOOLS and is_critic(tool_input.get("subagent_type")):
                    critic_launched = True
                elif name in EDIT_TOOLS:
                    path, lines = edit_size(name, tool_input, cwd)
                    if path:
                        edits[path] = edits.get(path, 0) + lines
        elif is_human_prompt(entry):
            prompt_ts = parse_ts(entry.get("timestamp"))
            if prompt_ts is None:
                return None
            prompt_id = str(entry.get("uuid") or entry.get("promptId") or entry.get("timestamp"))
            return Turn(prompt_ts, prompt_id, critic_launched, edits)
    return None


def git(root, *args):
    try:
        result = subprocess.run(
            ["git", "-C", root, "-c", "core.quotePath=false"] + list(args),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, timeout=GIT_TIMEOUT, env=GIT_ENV,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout if result.returncode == 0 else None


def project_root(cwd):
    out = git(cwd, "rev-parse", "--show-toplevel")
    if out and out.strip():
        return os.path.realpath(os.fsdecode(out.strip())), True
    return os.path.realpath(cwd), False


def git_candidates(root, since):
    """Грязные и неотслеживаемые файлы плюс файлы из коммитов за ход. Значение — статус git или "log"."""
    found = {}
    out = git(root, "status", "--porcelain=v1", "-z", "--untracked-files=all")
    tokens = out.split(b"\0") if out else []
    i = 0
    while i < len(tokens):
        token = tokens[i]
        i += 1
        if len(token) < 4:
            continue
        status = token[:2]
        if b"R" in status or b"C" in status:
            i += 1  # следом идёт исходный путь переименования
        found[os.path.realpath(os.path.join(root, os.fsdecode(token[3:])))] = os.fsdecode(status)
    out = git(root, "log", "--since=@%d" % int(since), "--name-only", "--no-renames", "--format=")
    for line in out.splitlines() if out else []:
        if line.strip():
            found.setdefault(os.path.realpath(os.path.join(root, os.fsdecode(line))), "log")
    return found


def walk_candidates(root, since):
    """Без git: файлы рабочего каталога с mtime после запроса. Значение — "new" или "changed"."""
    found = {}
    if root in (os.path.realpath(os.path.expanduser("~")), os.path.realpath(os.sep)):
        return found
    deadline = time.monotonic() + WALK_MAX_SECONDS
    seen = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in dirnames if name not in SKIP_DIRS]
        for name in filenames:
            path = os.path.join(dirpath, name)
            st = file_stat(path)
            if st is not None and st.st_mtime >= since:
                found[os.path.realpath(path)] = "new" if getattr(st, "st_birthtime", 0) >= since else "changed"
        seen += len(filenames)
        if seen > WALK_MAX_FILES or time.monotonic() > deadline:
            break
    return found


def file_stat(path):
    try:
        st = os.stat(path)
    except OSError:
        return None
    return st if stat.S_ISREG(st.st_mode) else None


def read_text(path):
    """Содержимое текстового файла до 1 МБ, иначе None."""
    try:
        if os.path.getsize(path) > MAX_COUNTED_BYTES:
            return None
        with open(path, "rb") as source:
            data = source.read()
    except OSError:
        return None
    return None if b"\0" in data[:8000] else data


def relative_inside(root, path):
    rel = os.path.relpath(path, root)
    if rel == os.curdir or rel == os.pardir or rel.startswith(os.pardir + os.sep):
        return None
    return rel.replace(os.sep, "/")


def is_production(rel):
    parts = rel.split("/")
    if any(part in SKIP_DIRS for part in parts[:-1]):
        return False
    name = parts[-1]
    if name in LOCKFILES or name.upper() in DOC_NAMES:
        return False
    ext = os.path.splitext(name)[1].lower()
    if ext in DOC_EXT or ext in NON_CODE_EXT:
        return False
    return not TEST_RE.search(rel)


def is_tooling(root, path, cache):
    """Файл внутри пакета скилла или плагина Claude Code: это инструмент, а не прод-код."""
    directory = os.path.dirname(path)
    visited = []
    result = False
    while True:
        if directory in cache:
            result = cache[directory]
            break
        visited.append(directory)
        if os.path.isfile(os.path.join(directory, "SKILL.md")) or os.path.isdir(os.path.join(directory, ".claude-plugin")):
            result = True
            break
        parent = os.path.dirname(directory)
        if directory == root or parent == directory:
            break
        directory = parent
    for seen in visited:
        cache[seen] = result
    return result


def is_generated(path):
    try:
        with open(path, "rb") as source:
            head = source.read(2048).lower()
    except OSError:
        return False
    return GENERATED_RE.search(head) is not None


def trivial_prefixes(rel):
    name = rel.rsplit("/", 1)[-1]
    ext = os.path.splitext(name)[1].lower()
    comments = COMMENT_MARKERS.get(ext) or NAME_COMMENT_MARKERS.get(name, ())
    return comments + (IMPORT_PREFIXES if ext in IMPORT_EXT else ())


def is_trivial_line(text, prefixes):
    stripped = text.strip()
    return not stripped or stripped.startswith(prefixes)


def substantive_lines(rel, data):
    """Строки нового файла без пустых, комментариев, import и package."""
    prefixes = trivial_prefixes(rel)
    return sum(1 for line in data.decode("utf-8", "replace").splitlines() if not is_trivial_line(line, prefixes))


def header_path(line):
    """Путь из `diff --git a/<p> b/<p>`; с --no-renames половины совпадают. Пути в кавычках — None."""
    body = line[len("diff --git a/"):] if line.startswith("diff --git a/") else ""
    half = (len(body) - 3) // 2
    if half > 0 and body[half:half + 3] == " b/" and body[:half] == body[half + 3:]:
        return body[:half]
    return None


def diff_against_head(root, rels):
    """Существенные строки `git diff HEAD` по файлам: rel -> [добавлено, удалено].

    Пробелы и пустые строки git отбрасывает сам (-w, --ignore-blank-lines), комментарии,
    import и package — is_trivial_line. Файла нет в ответе — существенных правок нет.
    None — разбора нет, и файлы считаются как раньше: нет коммитов, файлов слишком много
    или путь из diff не удалось сопоставить.
    """
    if not rels or len(rels) > MAX_DIFF_FILES:
        return None
    out = git(root, "diff", "HEAD", "-U0", "-w", "--ignore-blank-lines", "--no-color", "--no-ext-diff",
              "--no-renames", "--", *rels)
    if out is None:
        return None
    stats = dict((rel, [0, 0]) for rel in rels)
    current, prefixes, in_hunk = None, (), False
    for raw in out.split(b"\n"):
        line = raw.decode("utf-8", "replace")
        if line.startswith("diff --git "):
            current, in_hunk = header_path(line), False
            if current not in stats:
                return None  # при сомнении считаем файл, а не пропускаем
            prefixes = trivial_prefixes(current)
        elif line.startswith("Binary files ") and current is not None:
            stats[current] = [1, 1]
        elif line.startswith("@@"):
            in_hunk = True
        elif in_hunk and current is not None and line[:1] in ("+", "-"):
            if not is_trivial_line(line[1:], prefixes):
                stats[current][0 if line[0] == "+" else 1] += 1
    return stats


def measure(root, is_git, turn):
    since = turn.prompt_ts - CLOCK_SKEW
    candidates = git_candidates(root, since) if is_git else walk_candidates(root, since)
    for path in turn.edits:
        candidates.setdefault(path, "edit")
    tooling_cache = {}
    changed = []  # (path, rel, статус)
    for path, status in candidates.items():
        rel = relative_inside(root, path)
        if rel is None or not is_production(rel):
            continue
        st = file_stat(path)
        if st is None or st.st_mtime < since:
            continue
        if is_tooling(root, path, tooling_cache) or is_generated(path):
            continue
        changed.append((path, rel, status))
    # В diff — только отслеживаемые и изменённые сейчас: у коммитов за ход и новых файлов своя оценка.
    diff = diff_against_head(root, [rel for _, rel, status in changed if status not in ("??", "log", "edit")]) \
        if is_git else None
    prod, risky = [], []
    for path, rel, status in changed:
        from_tools = turn.edits.get(path, 0)
        if diff is not None and rel in diff:
            lines = max(diff[rel])
            if lines == 0:
                continue  # только пробелы, комментарии, import
            if from_tools:
                lines = min(lines, from_tools)  # diff может включать правки до этого запроса
        elif status in ("??", "new"):
            data = read_text(path)
            lines = substantive_lines(rel, data) if data is not None else from_tools
            if data is not None and lines == 0:
                continue  # новый файл из одних комментариев
        else:
            lines = from_tools
        prod.append((rel, lines))
        if MIGRATION_RE.search(rel) or SECURITY_RE.search(rel):
            risky.append(rel)
    prod.sort()
    risky.sort()
    return prod, risky


def state_file(session_id):
    return os.path.join(STATE_DIR, re.sub(r"[^A-Za-z0-9_.-]", "_", session_id) or "unknown")


def already_reminded(session_id, prompt_id):
    try:
        with open(state_file(session_id), encoding="utf-8") as state:
            return state.read().strip() == prompt_id
    except OSError:
        return False


def remember_reminder(session_id, prompt_id):
    try:
        os.makedirs(STATE_DIR, exist_ok=True)
        with open(state_file(session_id), "w", encoding="utf-8") as state:
            state.write(prompt_id)
    except OSError:
        pass


def build_reason(prod, total_lines, risky):
    shown = [rel for rel, _ in prod[:SHOWN_FILES]]
    files = ", ".join(shown)
    if len(prod) > len(shown):
        files += " и ещё %d" % (len(prod) - len(shown))
    stats = "production-файлов: %d" % len(prod)
    if total_lines:
        stats += ", изменённых строк: ~%d" % total_lines
    if risky:
        stats += "; затронуты миграции или безопасность: " + ", ".join(risky[:SHOWN_FILES])
    return (
        "critic-gate: изменение похоже на задачу размера M или L, а агент {agent} с последнего запроса "
        "пользователя не запускался. Изменено {stats}.\n"
        "Файлы: {files}\n\n"
        "Перед итоговым ответом запусти агента {agent} (Agent, subagent_type: \"{agent}\") по этим изменениям. "
        "Передай ему область diff или список файлов, 2–5 строк о том, что сделано, требования или спеку, "
        "если они есть, размер задачи и что известно о проде: нагрузку, объёмы данных, потребителей API "
        "и событий, способ деплоя. Подтверждённые блокеры исправь (баг — сначала тест), риски и вопросы "
        "вынеси пользователю.\n"
        "Если критик здесь не нужен — механическая правка, переименование, форматирование, сгенерированный "
        "код, — одной строкой скажи пользователю почему и заверши ход. Если агента {agent} нет среди "
        "доступных, скажи пользователю, что его нужно положить в ~/.claude/agents/ и начать новую сессию."
    ).format(agent=AGENT, stats=stats, files=files)


def main():
    try:
        payload = json.load(sys.stdin)
    except ValueError:
        return
    if not isinstance(payload, dict) or payload.get("stop_hook_active"):
        return
    if os.environ.get("CRITIC_GATE", "").strip().lower() in ("0", "off", "false", "no"):
        return
    transcript = payload.get("transcript_path")
    if not isinstance(transcript, str) or not os.path.isfile(transcript):
        return
    cwd = payload.get("cwd") if isinstance(payload.get("cwd"), str) else os.getcwd()
    turn = read_turn(transcript, cwd)
    if turn is None or turn.critic_launched:
        return
    session_id = str(payload.get("session_id") or "unknown")
    if already_reminded(session_id, turn.prompt_id):
        return
    root, is_git = project_root(cwd)
    prod, risky = measure(root, is_git, turn)
    total_lines = sum(lines for _, lines in prod)
    if len(prod) < MIN_FILES and total_lines < MIN_LINES and not risky:
        return
    remember_reminder(session_id, turn.prompt_id)
    # ASCII-JSON: вывод не зависит от локали процесса хука
    print(json.dumps({"decision": "block", "reason": build_reason(prod, total_lines, risky)}))


if __name__ == "__main__":
    try:
        main()
    except Exception:  # хук не должен ломать сессию
        if os.environ.get("CRITIC_GATE_DEBUG"):
            traceback.print_exc()
    sys.exit(0)
